name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Release
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/vimlink"
