name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vimlink
        path: target/release/vimlink

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
    - name: Download Release Artifact
      uses: actions/download-artifact@v4
      with:
        name: vimlink
        path: target/release/
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/vimlink"
